---
ID: "ff4555c5-8424-4eb9-96a3-b96a01764f79"
Parent: "d855f8c7-8205-4b6b-9d97-91d94d3927e0"
Template: "d855f8c7-8205-4b6b-9d97-91d94d3927e0"
Path: /sitecore/templates/Feature/projectarchive/Datasource Templates/Global/IFrame/Iframe/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231029T085102Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "372b08e7-bddf-4e74-a023-3848566e1c6e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231029T085102Z
